- hosts: "{{ vm_name }}" 
  gather_facts: true
  connection: local

  tasks:
    - name: install updates
#     become: yes
#     become_user: root
      yum: 
        name: '*' 
        state: latest 
        use_backend: yum4

